# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Web Design and Usability AVT 415
email: agarci44@gmu.edu
description: Course site for AVT 415
baseurl: "/advanced-web-design" # the subpath of your site, e.g. /blog
url: "http://thehonestape.github.io/" # the base hostname & protocol for your site
github_username:  thehonestape

# Build settings
markdown: kramdown
